apiVersion: v1
kind: Namespace
metadata:
  name: inworldai-discord

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: inworldai-redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inworldai-redis
  template:
    metadata:
      labels:
        app: inworldai-redis
    spec:
      containers:
      - name: redis
        image: redis:6.2.5-alpine
        ports:
        - containerPort: 6379
        resources:
          limits:
            cpu: "0.1"
            memory: "128Mi"
        readinessProbe:
          exec:
            command:
            - redis-cli
            - ping
          initialDelaySeconds: 5
          periodSeconds: 10

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: inworldai-discord
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inworldai-discord
  template:
    metadata:
      labels:
        app: inworldai-discord
    spec:
      initContainers:
      - name: init-redis
        image: redis:6.2.5-alpine
        env:
        - name: REDIS_HOST
          value: inworldai-redis
        command:
        - sh
        - -c
        - |
          until redis-cli -h $REDIS_HOST ping; do sleep 1; done
        resources:
          limits:
            cpu: "0.1"
            memory: "128Mi"
      containers:
      - name: inworldai-discord 
        image: "devopswithbrian/inworldai-discord:0.20.1"
        imagePullPolicy: Always
        tty: true
        env:
          - name: PYTHONUNBUFFERED
            value: "0"
          - name: DISCORD_BOT_TOKEN
            valueFrom:
              secretKeyRef:
                name: inworldai-discord-prd
                key: DISCORD_BOT_TOKEN
          - name: INWORLD_KEY
            valueFrom:
              secretKeyRef:
                name: inworldai-discord-prd
                key: INWORLD_KEY
          - name: INWORLD_SECRET
            valueFrom:
              secretKeyRef:
                name: inworldai-discord-prd
                key: INWORLD_SECRET
          - name: INWORLD_SCENE
            valueFrom:
              secretKeyRef:
                name: inworldai-discord-prd
                key: INWORLD_SCENE
          - name: REDIS_HOST
            value: inworldai-redis
        resources:
          limits:
            cpu: "0.5"
            memory: "512Mi"
        readinessProbe:
          exec:
            command:
            - redis-cli
            - ping
          initialDelaySeconds: 5
          periodSeconds: 10
---
